var SUPPORTED_LANGS = ["en", "es"];
var currentLang = localStorage.getItem("twm_lang") || ((navigator.language || "").startsWith("es") ? "es" : "en");

var TRANSLATIONS = {
  en: {
    lang_button: "ES",
    lang_button_label: "Switch to Spanish",
    nav_home: "Home",
    nav_phone_cases: "Phone Cases",
    nav_repairs: "Repairs",
    nav_about: "About",
    nav_about_us: "About Us",
    nav_contact: "Contact",
    nav_privacy: "Privacy",
    nav_privacy_policy: "Privacy Policy",
    nav_terms: "Terms",
    nav_delivery: "Delivery Info",
    nav_products: "Products",
    nav_screen_protectors: "Screen Protectors",
    nav_accessories: "Accessories",
    nav_custom_photo_cover: "Custom Photo Cover",
    nav_browse_catalog: "Browse Catalog",
    nav_express_repairs: "Express Repairs",
    nav_special_deals: "Special Deals",
    nav_iphone_covers: "iPhone Covers",
    nav_samsung_covers: "Samsung Covers",
    nav_redmi_covers: "Redmi Covers",
    nav_oppo_covers: "Oppo Covers",
    nav_google_pixel: "Google Pixel",
    nav_airpod_covers: "AirPod Covers",
    nav_camera_protectors: "Camera Protectors",
    nav_smart_watches: "Smart Watches",
    nav_watch_bands: "Watch Bands",
    nav_headphones: "Headphones",
    nav_speakers: "Speakers",
    nav_mobile_accessories: "Mobile Accessories",
    nav_cordon: "Cordon",
    nav_travel_adapter: "Travel Adapter",
    nav_memory_cards: "Memory Cards",
    nav_mobile_repair: "Mobile Repair",
    global_search_placeholder: "Search products, brands, models...",
    search_category_placeholder: "Search this category...",
    search_products_placeholder: "Search products...",
    hero_tag: "PROTECT | ACCESSORIZE | ELEVATE",
    hero_title: "Custom mobile case printing available",
    hero_desc: "Create personalized covers with premium-quality printing for photos, logos, names, anime art, couple pictures, business branding, and custom designs.",
    hero_shop_covers: "Shop Covers",
    hero_whatsapp_now: "WhatsApp Now",
    hero_card_custom: "Custom photo cases",
    hero_card_spain_store: "Spain store",
    hero_card_new_arrivals: "New arrivals",
    hero_trust_1: "5-Star 4.9 Rating",
    hero_trust_2: "5000+ Repairs",
    hero_trust_3: "Same-Day Service",
    feature_quality_title: "Genuine Quality",
    feature_quality_text: "Top-tier components & covers",
    feature_repair_title: "1-Hour Repair",
    feature_repair_text: "Instant screen & battery swap",
    feature_shipping_title: "Free Shipping",
    feature_shipping_text: "On orders above €50.00",
    feature_whatsapp_title: "WhatsApp Ordering",
    feature_whatsapp_text: "Fast support and easy checkout",
    category_products_tag: "FEATURED SELECTION",
    category_products_title: "Trending Products",
    category_products_desc: "Bestselling covers, adapters, screen protectors, headphones & accessories you'll love.",
    repair_title: "Professional Repairs",
    repair_desc: "Our technicians specialize in screen replacements, complex back glass swaps, battery replacement, and charging connectors. We use premium certified components.",
    repair_card_tag: "Express Diagnostics",
    repair_card_title: "Calculate Repair Cost",
    repair_card_desc: "Select your brand, model, and screen/component failure to see an instant quotation estimation.",
    repair_brand_label: "1. Device Brand",
    repair_brand_placeholder: "Select Phone Brand...",
    repair_model_label: "2. Device Model",
    repair_model_placeholder: "Select Phone Model...",
    repair_issue_label: "3. Component Issue",
    repair_issue_placeholder: "Select Repair Issue...",
    estimate_charge: "Estimated Charge",
    estimate_duration: "Duration",
    booking_name_label: "Full Name",
    booking_name_placeholder: "Your name",
    booking_phone_label: "Phone Number (WhatsApp)",
    booking_phone_placeholder: "0034 674 002 687",
    booking_address_placeholder: "Full Delivery Address",
    book_repair_btn: "Book & Add Repair to Cart",
    offers_bundle_label: "Special Bundle Deal",
    offers_bundle_title: "Premium Screen Protector<br>& MagSafe Cover Pack",
    offers_bundle_desc: "Buy any iPhone or Samsung case along with a 9H tempered glass screen protector and receive a €10 discount automatically!",
    offers_shop_bundle: "Shop Bundle",
    offers_flash_sale_label: "Flash Sale Ending Soon",
    offers_flash_sale_title: "Save 10% Storewide",
    offers_flash_sale_desc: "Use coupon code WELCOME10 at checkout to claim your opening discount.",
    contact_location_title: "Visit Our Location",
    contact_location_desc: "Drop by our retail store in Spain for support, sim cards, custom cases, or walk-in repairs.",
    contact_store_address_label: "Store Address",
    contact_customer_support_label: "Customer Support",
    contact_opening_hours_label: "Opening Hours",
    contact_navigation_btn: "Open Navigation Map",
    support_certified: "Certified Tech Support",
    footer_covers: "Covers & Cases",
    footer_smart_tech: "Smart Tech",
    footer_support: "Store Support",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_delivery: "Delivery Info",
    cart_shopping_cart: "Shopping Cart",
    cart_empty: "Your cart is empty",
    cart_continue: "Continue Shopping",
    cart_pickup: "Store Pickup (Free)",
    cart_delivery: "Home Delivery (€4.99)",
    cart_delivery_short: "Home Delivery",
    cart_free: "FREE",
    cart_promo_placeholder: "PROMO CODE",
    cart_apply_promo: "Apply",
    cart_subtotal: "Subtotal",
    cart_shipping: "Shipping",
    cart_coupon_discount: "Coupon Discount",
    cart_total: "Estimated Total",
    cart_checkout_whatsapp: "Checkout via WhatsApp",
    cart_decrease_qty: "Decrease quantity",
    cart_increase_qty: "Increase quantity",
    cart_remove_item: "Remove item",
    product_view: "View",
    product_add: "Add",
    modal_select_device: "Select Device Compatibility",
    modal_add_to_cart: "Add to Shopping Cart",
    quick_chat_label: "Chat with support on WhatsApp",
    quick_chat_text: "Ask on WhatsApp",
    no_products_found_title: "No Products Found",
    no_products_found_desc: "Try searching for something else or explore a different category.",
    product_not_found: "Product not found",
    product_not_found_desc: "This item is no longer available.",
    browse_products: "Browse Products",
    ask_on_whatsapp: "Ask on WhatsApp",
    category_page_badge: "Products",
    category_page_title: "Products",
    category_page_subtitle_all: "Browse all premium covers, accessories, protectors, phones, watches, and repair essentials in one place.",
    category_page_subtitle_category: "Browse {category} available at The World Mobile.",
    category_products_header_tag: "CATEGORY PRODUCTS",
    available_items_title: "Available Items",
    available_items_desc: "Choose a product, view details, and add it to your cart.",
    loading_products: "Loading products...",
    product_detail_title: "Product details",
    product_detail_loading: "Loading product details...",
    toast_select_issue: "Please select a brand, model, and issue to continue.",
    toast_enter_name_phone: "Please enter your name and WhatsApp number.",
    toast_repair_added: "Repair booking added to cart!",
    toast_promo_empty: "Please enter a promo code first.",
    toast_coupon_valid: "Coupon applied! 10% discount activated.",
    toast_coupon_free_ship: "Free shipping coupon applied!",
    toast_coupon_repair: "€5.00 off your repair booking applied!",
    toast_cart_empty: "Your cart is empty!",
    toast_coupon_invalid: "\"{code}\" is not a valid coupon code.",
    toast_product_added: "{product} added to cart!",
    toast_repair_added_model: "Repair booking for {model} added to cart!",
    order_customer_name: "Customer Name",
    order_phone: "Phone",
    order_delivery_method: "Delivery Method",
    order_shipping_address: "Shipping Address",
    order_new_title: "NEW ORDER - THE WORLD MOBILE",
    order_items: "Ordered Items",
    order_phone_model: "Phone Model",
    order_text: "Text",
    order_case_color: "Case Color",
    order_repair: "Repair",
    order_device: "Device",
    order_selected_model: "Selected Model",
    order_shipping_fee: "Shipping Fee",
    order_confirm: "Please confirm my order and send payment instructions. Thank you!",
    about_title: "About The World Mobile",
    about_intro: "We are a premium mobile accessories and repair store serving customers across Spain with fast repairs, custom phone covers, and modern tech essentials. Our mission is to deliver quality products, reliable service, and a seamless mobile shopping experience.",
    about_offer_title: "What we offer",
    about_offer_1: "Custom Phone Cases:",
    about_offer_1_desc: "Personalized photo covers and designer cases.",
    about_offer_2: "Express Repairs:",
    about_offer_2_desc: "Screen replacements, battery swaps, and connector repairs.",
    about_offer_3: "Accessories:",
    about_offer_3_desc: "Chargers, headphones, watch bands, SIM cards, and more.",
    about_offer_4: "Trusted Service:",
    about_offer_4_desc: "Same-day repair and WhatsApp support for easy orders.",
    about_more: "We design every item to be affordable, reliable, and ready to use. Whether you need fast repair service or a new accessory, The World Mobile is your trusted local partner.",
    about_contact_us: "Contact Us",
    contact_title: "Contact The World Mobile",
    contact_intro: "If you have questions about orders, repairs, or product availability, our team is ready to help.",
    contact_store_location_title: "Store Location",
    contact_store_location_desc: "Carrer de Lepant, 322, Eixample, 08025 Barcelona, Spain",
    contact_whatsapp_support_title: "WhatsApp Support",
    contact_whatsapp_support_desc: "0034 674 002 687",
    contact_email_title: "Email",
    contact_email_desc: "Theworldmobile2@gmail.com",
    contact_back_to_shop: "Back to Shop",
    delivery_title: "Delivery Information",
    delivery_intro: "We offer store pickup and home delivery across Spain.",
    delivery_pickup: "Pickup",
    delivery_pickup_desc: "Pickup is free at our Barcelona store: Carrer de Lepant, 322, Eixample, 08025 Barcelona, Spain. Orders are usually ready within 2-4 hours after confirmation.",
    delivery_home: "Home Delivery",
    delivery_home_desc: "Delivery costs €4.99 and typically takes 1-2 business days within Spain. We deliver to major cities and surrounding areas.",
    delivery_tracking: "Tracking",
    delivery_tracking_desc: "After placing an order, we will share tracking details via WhatsApp or email when your package is dispatched.",
    delivery_back_home: "Back to Home",
    privacy_title: "Privacy Policy",
    privacy_intro: "Your privacy is important to us. This policy explains how The World Mobile collects, uses, and protects your information when you visit our website.",
    privacy_collect: "What we collect",
    privacy_collect_desc: "Contact details when you place orders or use the WhatsApp checkout.",
    privacy_collect_desc2: "Shipping address when you choose delivery.",
    privacy_collect_desc3: "Basic device and product preferences for a personalized shopping experience.",
    privacy_use: "How we use your data",
    privacy_use_desc: "We use your information to process orders, manage deliveries, and respond to support requests. We do not sell your personal data to third parties.",
    privacy_security: "Security",
    privacy_security_desc: "We follow best practices to keep your data safe, including secure checkout links and secure communication channels.",
    privacy_back_home: "Back to Home",
    terms_title: "Terms of Service",
    terms_intro: "Welcome to The World Mobile. By using this website and placing orders, you agree to our terms and conditions.",
    terms_ordering: "Ordering",
    terms_ordering_desc: "All orders are subject to product availability and confirmation of payment. We reserve the right to refuse service for any reason.",
    terms_repairs: "Repairs and Fulfillment",
    terms_repairs_desc: "Repair price estimates are provided for guidance and may vary after inspection. Delivery times are estimates and may change based on order volume.",
    terms_returns: "Returns and Refunds",
    terms_returns_desc: "We offer refunds or exchanges for damaged or incorrect items when reported within 7 days. Repairs are covered under our warranty terms.",
    terms_back_home: "Back to Home"
  },
  es: {
    lang_button: "EN",
    lang_button_label: "Cambiar a inglés",
    nav_home: "Inicio",
    nav_phone_cases: "Fundas",
    nav_repairs: "Reparaciones",
    nav_about: "Acerca de",
    nav_about_us: "Sobre nosotros",
    nav_contact: "Contacto",
    nav_privacy: "Privacidad",
    nav_privacy_policy: "Política de privacidad",
    nav_terms: "Términos",
    nav_delivery: "Envío",
    nav_products: "Productos",
    nav_screen_protectors: "Protectores de pantalla",
    nav_accessories: "Accesorios",
    nav_custom_photo_cover: "Funda personalizada",
    nav_browse_catalog: "Ver catálogo",
    nav_express_repairs: "Reparaciones exprés",
    nav_special_deals: "Ofertas especiales",
    nav_iphone_covers: "Fundas iPhone",
    nav_samsung_covers: "Fundas Samsung",
    nav_redmi_covers: "Fundas Redmi",
    nav_oppo_covers: "Fundas Oppo",
    nav_google_pixel: "Google Pixel",
    nav_airpod_covers: "Fundas AirPod",
    nav_camera_protectors: "Protectores de cámara",
    nav_smart_watches: "Relojes inteligentes",
    nav_watch_bands: "Correas de reloj",
    nav_headphones: "Auriculares",
    nav_speakers: "Altavoces",
    nav_mobile_accessories: "Accesorios móviles",
    nav_cordon: "Cordon",
    nav_travel_adapter: "Adaptador de viaje",
    nav_memory_cards: "Tarjetas de memoria",
    nav_mobile_repair: "Reparación móvil",
    global_search_placeholder: "Buscar productos, marcas o modelos...",
    search_category_placeholder: "Buscar en esta categoría...",
    search_products_placeholder: "Buscar productos...",
    hero_tag: "PROTEGER | ACCESORIZAR | ELEVAR",
    hero_title: "Impresión de fundas móviles personalizadas disponible",
    hero_desc: "Crea fundas personalizadas con impresión de alta calidad para fotos, logos, nombres, arte anime, fotos de pareja, marca comercial y diseños exclusivos.",
    hero_shop_covers: "Comprar fundas",
    hero_whatsapp_now: "WhatsApp ahora",
    hero_card_custom: "Fundas personalizadas",
    hero_card_spain_store: "Tienda en España",
    hero_card_new_arrivals: "Nuevas llegadas",
    hero_trust_1: "Valoración 4.9 de 5",
    hero_trust_2: "Más de 5000 reparaciones",
    hero_trust_3: "Servicio el mismo día",
    feature_quality_title: "Calidad genuina",
    feature_quality_text: "Componentes y fundas de primera",
    feature_repair_title: "Reparación en 1 hora",
    feature_repair_text: "Cambio de pantalla y batería al instante",
    feature_shipping_title: "Envío gratis",
    feature_shipping_text: "En pedidos superiores a €50.00",
    feature_whatsapp_title: "Pedido por WhatsApp",
    feature_whatsapp_text: "Atención rápida y pago fácil",
    category_products_tag: "SELECCIÓN DESTACADA",
    category_products_title: "Productos de tendencia",
    category_products_desc: "Fundas, accesorios, protectores y más que te encantarán.",
    repair_title: "Reparaciones profesionales",
    repair_desc: "Nuestros técnicos son especialistas en reemplazos de pantalla, cambios de cristal trasero, baterías y conectores de carga. Utilizamos componentes certificados.",
    repair_card_tag: "Diagnóstico exprés",
    repair_card_title: "Calcula el costo de reparación",
    repair_card_desc: "Selecciona tu marca, modelo y tipo de daño para ver una cotización instantánea.",
    repair_brand_label: "1. Marca del dispositivo",
    repair_brand_placeholder: "Selecciona marca de teléfono...",
    repair_model_label: "2. Modelo del dispositivo",
    repair_model_placeholder: "Selecciona modelo...",
    repair_issue_label: "3. Problema del componente",
    repair_issue_placeholder: "Selecciona tipo de reparación...",
    estimate_charge: "Costo estimado",
    estimate_duration: "Duración",
    booking_name_label: "Nombre completo",
    booking_name_placeholder: "Tu nombre",
    booking_phone_label: "Número de WhatsApp",
    booking_phone_placeholder: "0034 674 002 687",
    booking_address_placeholder: "Dirección completa de entrega",
    book_repair_btn: "Reservar y añadir reparación al carrito",
    offers_bundle_label: "Oferta especial",
    offers_bundle_title: "Protector de pantalla premium<br>& pack de funda MagSafe",
    offers_bundle_desc: "Compra cualquier funda de iPhone o Samsung con vidrio templado 9H y consigue €10 de descuento automáticamente!",
    offers_shop_bundle: "Comprar paquete",
    offers_flash_sale_label: "Oferta relámpago",
    offers_flash_sale_title: "Ahorra 10% en toda la tienda",
    offers_flash_sale_desc: "Usa el cupón WELCOME10 en el pago para obtener tu descuento de apertura.",
    contact_location_title: "Visita nuestra ubicación",
    contact_location_desc: "Ven a nuestra tienda en España para soporte, SIM cards, fundas personalizadas o reparaciones sin cita.",
    contact_store_address_label: "Dirección de la tienda",
    contact_customer_support_label: "Atención al cliente",
    contact_opening_hours_label: "Horario",
    contact_navigation_btn: "Abrir mapa de navegación",
    support_certified: "Soporte técnico certificado",
    footer_covers: "Fundas y casos",
    footer_smart_tech: "Tecnología",
    footer_support: "Soporte de la tienda",
    footer_privacy: "Política de privacidad",
    footer_terms: "Términos de servicio",
    footer_delivery: "Información de envío",
    cart_shopping_cart: "Carrito de compras",
    cart_empty: "Tu carrito está vacío",
    cart_continue: "Seguir comprando",
    cart_pickup: "Recogida en tienda (gratis)",
    cart_delivery: "Entrega a domicilio (€4.99)",
    cart_delivery_short: "Entrega a domicilio",
    cart_free: "GRATIS",
    cart_promo_placeholder: "CÓDIGO PROMO",
    cart_apply_promo: "Aplicar",
    cart_subtotal: "Subtotal",
    cart_shipping: "Envío",
    cart_coupon_discount: "Descuento del cupón",
    cart_total: "Total estimado",
    cart_checkout_whatsapp: "Pagar por WhatsApp",
    cart_decrease_qty: "Disminuir cantidad",
    cart_increase_qty: "Aumentar cantidad",
    cart_remove_item: "Eliminar artículo",
    product_view: "Ver",
    product_add: "Añadir",
    modal_select_device: "Selecciona compatibilidad del dispositivo",
    modal_add_to_cart: "Añadir al carrito",
    quick_chat_label: "Chatear con soporte en WhatsApp",
    quick_chat_text: "Consultar por WhatsApp",
    no_products_found_title: "No se encontraron productos",
    no_products_found_desc: "Prueba otra búsqueda o cambia de categoría.",
    product_not_found: "Producto no encontrado",
    product_not_found_desc: "Este artículo ya no está disponible.",
    browse_products: "Ver productos",
    ask_on_whatsapp: "Preguntar por WhatsApp",
    category_page_badge: "Productos",
    category_page_title: "Productos",
    category_page_subtitle_all: "Explora fundas, accesorios, protectores, teléfonos, relojes y esenciales de reparación en un solo lugar.",
    category_page_subtitle_category: "Explora {category} disponibles en The World Mobile.",
    category_products_header_tag: "PRODUCTOS DE LA CATEGORÍA",
    available_items_title: "Artículos disponibles",
    available_items_desc: "Elige un producto, mira los detalles y añádelo a tu carrito.",
    loading_products: "Cargando productos...",
    product_detail_title: "Detalles del producto",
    product_detail_loading: "Cargando detalles del producto...",
    toast_select_issue: "Selecciona marca, modelo y problema para continuar.",
    toast_enter_name_phone: "Introduce tu nombre y número de WhatsApp.",
    toast_repair_added: "¡Reserva de reparación añadida al carrito!",
    toast_promo_empty: "Primero introduce un código promocional.",
    toast_coupon_valid: "¡Cupón aplicado! Descuento del 10% activado.",
    toast_coupon_free_ship: "¡Cupón de envío gratis aplicado!",
    toast_coupon_repair: "¡Se aplicaron €5.00 de descuento a tu reparación!",
    toast_cart_empty: "¡Tu carrito está vacío!",
    toast_coupon_invalid: "\"{code}\" no es un código de cupón válido.",
    toast_product_added: "¡{product} añadido al carrito!",
    toast_repair_added_model: "¡La reparación de {model} se añadió al carrito!",
    order_customer_name: "Nombre del cliente",
    order_phone: "Teléfono",
    order_delivery_method: "Método de entrega",
    order_shipping_address: "Dirección de envío",
    order_new_title: "NUEVO PEDIDO - THE WORLD MOBILE",
    order_items: "Artículos pedidos",
    order_phone_model: "Modelo del teléfono",
    order_text: "Texto",
    order_case_color: "Color de la funda",
    order_repair: "Reparación",
    order_device: "Dispositivo",
    order_selected_model: "Modelo seleccionado",
    order_shipping_fee: "Gasto de envío",
    order_confirm: "Por favor confirma mi pedido y envía las instrucciones de pago. ¡Gracias!",
    about_title: "Acerca de The World Mobile",
    about_intro: "Somos una tienda premium de accesorios móviles y reparaciones que atiende clientes en España con reparaciones rápidas, fundas personalizadas y tecnología moderna. Nuestra misión es ofrecer productos de calidad, servicio confiable y una experiencia de compra fluida.",
    about_offer_title: "Lo que ofrecemos",
    about_offer_1: "Fundas personalizadas:",
    about_offer_1_desc: "Fundas con foto y diseño exclusivo.",
    about_offer_2: "Reparaciones exprés:",
    about_offer_2_desc: "Cambios de pantalla, baterías y conectores.",
    about_offer_3: "Accesorios:",
    about_offer_3_desc: "Cargadores, auriculares, correas para reloj, tarjetas SIM y más.",
    about_offer_4: "Servicio confiable:",
    about_offer_4_desc: "Reparación el mismo día y soporte por WhatsApp.",
    about_more: "Diseñamos cada artículo para que sea asequible, confiable y listo para usar. Ya sea que necesites una reparación rápida o un nuevo accesorio, The World Mobile es tu socio local de confianza.",
    about_contact_us: "Contáctanos",
    contact_title: "Contacto The World Mobile",
    contact_intro: "Si tienes preguntas sobre pedidos, reparaciones o disponibilidad de productos, nuestro equipo está listo para ayudarte.",
    contact_store_location_title: "Ubicación de la tienda",
    contact_store_location_desc: "Carrer de Lepant, 322, Eixample, 08025 Barcelona, España",
    contact_whatsapp_support_title: "Soporte por WhatsApp",
    contact_whatsapp_support_desc: "0034 674 002 687",
    contact_email_title: "Correo electrónico",
    contact_email_desc: "Theworldmobile2@gmail.com",
    contact_back_to_shop: "Volver a la tienda",
    delivery_title: "Información de envío",
    delivery_intro: "Ofrecemos recogida en tienda y entrega a domicilio en toda España.",
    delivery_pickup: "Recogida",
    delivery_pickup_desc: "La recogida es gratis en nuestra tienda de Barcelona: Carrer de Lepant, 322, Eixample, 08025 Barcelona, España. Los pedidos suelen estar listos dentro de 2-4 horas tras la confirmación.",
    delivery_home: "Entrega a domicilio",
    delivery_home_desc: "La entrega cuesta €4.99 y normalmente tarda 1-2 días hábiles dentro de España. Entregamos en ciudades principales y áreas cercanas.",
    delivery_tracking: "Seguimiento",
    delivery_tracking_desc: "Después de realizar un pedido, compartiremos los detalles de seguimiento por WhatsApp o correo electrónico cuando tu paquete sea enviado.",
    delivery_back_home: "Volver al inicio",
    privacy_title: "Política de privacidad",
    privacy_intro: "Tu privacidad es importante para nosotros. Esta política explica cómo The World Mobile recopila, utiliza y protege tu información cuando visitas nuestro sitio web.",
    privacy_collect: "Lo que recopilamos",
    privacy_collect_desc: "Datos de contacto cuando realizas pedidos o usas el pago por WhatsApp.",
    privacy_collect_desc2: "Dirección de envío cuando eliges entrega.",
    privacy_collect_desc3: "Preferencias básicas de dispositivo y producto para una experiencia de compra personalizada.",
    privacy_use: "Cómo usamos tus datos",
    privacy_use_desc: "Utilizamos tu información para procesar pedidos, gestionar entregas y responder solicitudes de soporte. No vendemos tus datos personales a terceros.",
    privacy_security: "Seguridad",
    privacy_security_desc: "Seguimos las mejores prácticas para mantener tus datos seguros, incluyendo enlaces de pago seguros y canales de comunicación seguros.",
    privacy_back_home: "Volver al inicio",
    terms_title: "Términos de servicio",
    terms_intro: "Bienvenido a The World Mobile. Al usar este sitio web y realizar pedidos, aceptas nuestros términos y condiciones.",
    terms_ordering: "Pedidos",
    terms_ordering_desc: "Todos los pedidos están sujetos a disponibilidad de producto y confirmación de pago. Nos reservamos el derecho de rechazar el servicio por cualquier motivo.",
    terms_repairs: "Reparaciones y cumplimiento",
    terms_repairs_desc: "Las estimaciones de precio de reparación se ofrecen como referencia y pueden variar tras la inspección. Los tiempos de entrega son estimados y pueden cambiar según el volumen de pedidos.",
    terms_returns: "Devoluciones y reembolsos",
    terms_returns_desc: "Ofrecemos reembolsos o cambios por artículos dañados o incorrectos si se reporta dentro de 7 días. Las reparaciones están cubiertas por nuestros términos de garantía.",
    terms_back_home: "Volver al inicio"
  }
};

function getTranslation(key, fallback = "") {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) || fallback || key;
}

function translate(key, fallback = "", params = null) {
  var value = getTranslation(key, fallback);
  if (!params) return value;
  return Object.keys(params).reduce(function (text, param) {
    return text.replace(new RegExp("\\{" + param + "\\}", "g"), params[param] == null ? "" : String(params[param]));
  }, value);
}

function translatePage() {
  document.documentElement.lang = currentLang;
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var key = el.dataset.i18n;
    if (!key) return;
    var attr = el.dataset.i18nAttr || "text";
    var value = translate(key, el.textContent.trim());
    if (attr === "html") el.innerHTML = value;
    else if (attr === "placeholder") el.placeholder = value;
    else if (attr === "aria-label") el.setAttribute("aria-label", value);
    else if (attr === "value") el.value = value;
    else el.textContent = value;
  });
}

function updateLangToggle() {
  var btn = document.getElementById("lang-toggle-btn");
  if (!btn) return;
  btn.textContent = getTranslation("lang_button", btn.textContent);
  btn.setAttribute("aria-label", getTranslation("lang_button_label", btn.getAttribute("aria-label") || ""));
}

function setLanguage(lang) {
  if (!SUPPORTED_LANGS.includes(lang)) lang = "en";
  currentLang = lang;
  localStorage.setItem("twm_lang", currentLang);
  document.documentElement.lang = currentLang;
  if (typeof refreshLanguageTexts === "function") refreshLanguageTexts();
  translatePage();
  updateLangToggle();
  window.dispatchEvent(new CustomEvent("twm-language-change", { detail: { lang: currentLang } }));
}

function initLanguageSwitcher() {
  var header = document.querySelector(".shop-header .shop-container");
  if (!header) return;

  var actions = header.querySelector(".shop-actions");
  if (!actions) {
    actions = document.createElement("div");
    actions.className = "shop-actions";
    header.appendChild(actions);
  }

  var switcher = document.getElementById("lang-toggle-btn");
  if (!switcher) {
    switcher = document.createElement("button");
    switcher.type = "button";
    switcher.id = "lang-toggle-btn";
    switcher.className = "lang-toggle-btn";
    actions.insertBefore(switcher, actions.firstChild);
  }

  if (!switcher.dataset.bound) {
    switcher.addEventListener("click", function () {
      setLanguage(currentLang === "en" ? "es" : "en");
    });
    switcher.dataset.bound = "1";
  }

  updateLangToggle();
}

window.getTranslation = getTranslation;
window.translate = translate;
window.setLanguage = setLanguage;
window.initLanguageSwitcher = initLanguageSwitcher;
window.translatePage = translatePage;

document.addEventListener("DOMContentLoaded", function () {
  if (window.hasAppInit) return;
  initLanguageSwitcher();
  translatePage();
  updateLangToggle();
});
